export const ActionTypeGetData = {
    API_CALL_REQUEST: 'API_CALL_REQUEST',
    API_CALL_REQUEST_SUCCESS: 'API_CALL_REQUEST_SUCCESS',
    API_CALL_REQUEST_ERROR: 'API_CALL_REQUEST_ERROR',
    ADD_TODO : 'ADD_TODO',
    ADD_TODO_SUCCESS : 'ADD_TODO_SUCCESS',
    ADD_TODO_ERROR : 'ADD_TODO_ERROR',
    EDIT_TODO : 'EDIT_TODO',
    EDIT_TODO_SUCCESS : 'EDIT_TODO_SUCCESS',
    EDIT_TODO_ERROR : 'EDIT_TODO_ERROR',
    REMOVE_TODO_SUCCESS : 'REMOVE_TODO_SUCCESS',
    REMOVE_TODO : 'REMOVE_TODO',
    REMOVE_TODO_ERROR : 'REMOVE_TODO_ERROR',
    SEARCH_DATA: 'SEARCH_DATA'
}